name: morlor

services:  
  authelia:
    # See https://www.authelia.com/integration/proxies/nginx/
    image: 'authelia/authelia:latest'
    container_name: authelia
    restart: unless-stopped
    network_mode: host
    env_file: '/root/data/authelia/secrets.env'
    volumes:
      # Configuration files, database, etc.
      - /root/data/authelia:/config
    command:
      # Enables template replacement in the configuration file.
      - 'authelia'
      - '--config=/config/configuration.yml'
      - '--config.experimental.filters=template'

  reverse-proxy:
    # See https://hub.docker.com/_/nginx
    # See /docker/nginx-acme for details.
    image: 'nginx:1.29.2'
    container_name: reverse-proxy
    restart: unless-stopped        
    network_mode: host    
    volumes:
      # Configuration files
      - /root/luggage/morlor/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - /root/luggage/morlor/reverse-proxy/conf.d:/etc/nginx/conf.d
      - /root/luggage/morlor/reverse-proxy/snippets:/etc/nginx/snippets
      # HTTPS certificates
      - /root/data/certbot:/var/www/certbot
      - /root/data/letsencrypt:/etc/nginx/ssl
      # Static site files (new domains need to be properly configured!)
      - /root/luggage/morlor/www:/var/www

  canvas-socket:
    image: 'daemontus/canvas-socket-server'
    container_name: canvas-socket
    restart: always
    environment:
      - RUST_LOG=info
    ports:
      - "9000:9000"

  # Matrix services

  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    # Since synapse does not retry to connect to the database, restart upon
    # failure
    restart: unless-stopped
    # See the readme for a full documentation of the environment settings
    # NOTE: You must edit homeserver.yaml to use postgres, it defaults to sqlite
    networks:
      - synapse-net
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    depends_on:
      - authelia
      - synapse-db
    volumes:
      # For now, we will save everything to appdata; 
      # if it gets too big, we can always move it...
      - /root/data/matrix/data:/data
      - /root/data/matrix/mautrix-telegram:/mautrix-telegram
      - /root/data/matrix/mautrix-meta:/mautrix-meta
      - /root/data/matrix/mautrix-discord:/mautrix-discord
      - /root/data/matrix/mautrix-slack:/mautrix-slack
      - /root/data/matrix/mautrix-signal:/mautrix-signal
      - /root/data/matrix/mautrix-whatsapp:/mautrix-whatsapp
      - /root/data/matrix/mautrix-googlechat:/mautrix-googlechat
      # .. or you may split this between different storage points
      # - ./files:/data
      # - /path/to/ssd:/data/uploads
      # - /path/to/large_hdd:/data/media    
    ports:
      - 8008:8008/tcp
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '8G'

  synapse-db:
    image: docker.io/postgres:15-alpine
    # Change that password, of course!
    networks:
      - synapse-net
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${SYNAPSE_DB_PASSWORD}
      # ensure the database gets created correctly
      # https://element-hq.github.io/synapse/latest/postgres.html#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /root/data/matrix/db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '4G'

  mautrix-telegram:
    image: dock.mau.dev/mautrix/telegram:latest
    depends_on:
      - synapse-db
      - synapse
    networks:
      - synapse-net
    volumes:
      - /root/data/matrix/mautrix-telegram:/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'

  mautrix-meta:
    image: dock.mau.dev/mautrix/meta:latest
    depends_on:
      - synapse-db
      - synapse
    networks:
      - synapse-net
    volumes:
      - /root/data/matrix/mautrix-meta:/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'

  mautrix-discord:
    image: dock.mau.dev/mautrix/discord:latest
    depends_on:
      - synapse-db
      - synapse
    networks:
      - synapse-net
    volumes:
      - /root/data/matrix/mautrix-discord:/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'

  mautrix-slack:
    image: dock.mau.dev/mautrix/slack:latest
    depends_on:
      - synapse-db
      - synapse
    networks:
      - synapse-net
    volumes:
      - /root/data/matrix/mautrix-slack:/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'

  mautrix-signal:
    image: dock.mau.dev/mautrix/signal:latest
    depends_on:
      - synapse-db
      - synapse
    networks:
      - synapse-net
    volumes:
      - /root/data/matrix/mautrix-signal:/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'

  mautrix-whatsapp:
    image: dock.mau.dev/mautrix/whatsapp:latest
    depends_on:
      - synapse-db
      - synapse
    networks:
      - synapse-net
    volumes:
      - /root/data/matrix/mautrix-whatsapp:/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'

  mautrix-googlechat:
    image: dock.mau.dev/mautrix/googlechat:latest
    depends_on:
      - synapse-db
      - synapse
    networks:
      - synapse-net
    volumes:
      - /root/data/matrix/mautrix-googlechat:/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'

networks:
  synapse-net:
