name: morlor

services:  
  reverse-proxy:
    # See https://hub.docker.com/_/nginx
    # See /docker/nginx-acme for details.
    image: daemontus/nginx-acme:latest
    container_name: reverse-proxy
    restart: unless-stopped        
    network_mode: host
    volumes:
      # Configuration files
      - /root/luggage/morlor/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - /root/luggage/morlor/reverse-proxy/conf.d:/etc/nginx/conf.d      
      # HTTPS certificates
      - /root/data/certbot:/var/www/certbot
      - /root/data/letsencrypt:/etc/nginx/ssl
      # Static site files (new domains need to be properly configured!)
      - /root/luggage/morlor/www:/var/www      
