name: morlor

services:  
  reverse-proxy:
    # See https://hub.docker.com/_/nginx
    image: 'nginx:1.29.2'
    container_name: reverse-proxy
    restart: unless-stopped        
    network_mode: host
    volumes:
      # Configuration files
      - /root/luggage/morlor/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - /root/luggage/morlor/reverse-proxy/conf.d:/etc/nginx/conf.d      
      # Static site files (new domains need to be properly configured!)
      - /root/luggage/morlor/www:/var/www