#!/bin/bash

export AUTHELIA_JWT_SECRET=`op read op://TichaPosta/AUTHELIA_SECRETS/JWT_SECRET`
export AUTHELIA_SESSION_SECRET=`op read op://TichaPosta/AUTHELIA_SECRETS/SESSION_SECRET`
export AUTHELIA_STORAGE_KEY=`op read op://TichaPosta/AUTHELIA_SECRETS/STORAGE_KEY`
export AUTHELIA_SMTP_PASSWORD=`op read op://TichaPosta/AUTHELIA_SECRETS/SMTP_PASSWORD`
export AUTHELIA_OIDC_HMAC_SECRET=`op read op://TichaPosta/AUTHELIA_SECRETS/OIDC_HMAC_SECRET`
export AUTHELIA_OIDC_JWK_PRIVATE_KEY=`op read op://TichaPosta/AUTHELIA_SECRETS/JWK_PRIVATE_KEY`
export AUTHELIA_CLIENT_SECRET_SEAFILE=`op read op://TichaPosta/AUTHELIA_SECRETS/CLIENT_SECRET_SEAFILE`
export AUTHELIA_CLIENT_SECRET_IMMICH=`op read op://TichaPosta/AUTHELIA_SECRETS/CLIENT_SECRET_IMMICH`
export AUTHELIA_CLIENT_SECRET_SYNAPSE=`op read op://TichaPosta/AUTHELIA_SECRETS/CLIENT_SECRET_SYNAPSE`