server:
  cacheDir: /home/filebrowser/data/tmp # using the data volume so it can persist across restarts
  sources:
    - path: /srv/Media # Do not use a root "/" directory or include the "/var" folder
      config:
        defaultPermissions:
          view: true
          download: true
          modify: true      # enables rename/move/copy/delete of existing files
          create: true      # enables upload/new folders
          delete: true      # enables delete specifically
    - path: /srv/Archive
      config:
        defaultPermissions:
          view: true
          download: true
          modify: true      # enables rename/move/copy/delete of existing files
          create: true      # enables upload/new folders
          delete: true      # enables delete specifically
    - path: /srv/Personal
      config:
        defaultPermissions:
          view: true
          download: true
          modify: true      # enables rename/move/copy/delete of existing files
          create: true      # enables upload/new folders
          delete: true      # enables delete specifically
auth:
  methods:
    oidc:
      enabled: true
      clientId: filebrowser
      issuerUrl: https://auth.unsigned-short.com
      scopes: "openid email profile groups"
      userIdentifier: preferred_username   # default
      adminGroup: "admins"     # OIDC group that gets admin rights
      # userGroups:                        # optional: restrict login to these groups
      #   - "filebrowser-users"
      groupsClaim: groups                  # default
      logoutRedirectUrl: https://auth.unsigned-short.com/logout
http:
  #baseURL: "https://files.unsigned-short.com"
  trustProxyHeaders: true
