# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "unsigned-short.com"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
#database:
#  name: sqlite3
#  args:
#    database: /data/homeserver.db
database:
  name: psycopg2
  args:
    user: synapse
    password: ${DATABASE_PASSWORD}
    dbname: synapse
    host: synapse-db
    cp_min: 5
    cp_max: 10

app_service_config_files:
  - /mautrix-telegram/registration.yaml
  
log_config: "/data/unsigned-short.com.log.config"
media_store_path: /data/media_store
registration_shared_secret: "${REGISTRATION_SHARED_SECRET}"
report_stats: true
macaroon_secret_key: "${MACAROON_SECRET}"
form_secret: "${FORM_SECRET}"
signing_key_path: "/data/unsigned-short.com.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"

oidc_providers:
  - idp_id: authelia
    idp_name: 'Authelia'
    discover: true
    issuer: 'https://auth.unsigned-short.com'
    client_id: 'synapse'
    client_secret: '${AUTHELIA_CLIENT_SECRET}'
    scopes:
     - 'openid'
     - 'profile'
     - 'email'
     - 'groups'
    allow_existing_users: true
    user_mapping_provider:
      config:
        subject_claim: 'sub'
        localpart_template: "{{ user.preferred_username }}"        
        display_name_template: '{{ user.name }}'
        email_template: '{{ user.email }}'
    authorization_endpoint: "https://auth.unsigned-short.com/api/oidc/authorization"
    token_endpoint: "https://auth.unsigned-short.com/api/oidc/token"
    userinfo_endpoint: "https://auth.unsigned-short.com/api/oidc/userinfo"
    user_profile_method: "userinfo_endpoint"



# vim:ft=yaml
