services:
  celloracle:
    image: 'daemontus/software-cell-oracle:latest'
    ports: 
      - "10000:8888"
    volumes:
      - /nfs/ws-daemontus-hdd/software/celloracle:/root/notebook/remote
      - /media/local/notebook/celloracle:/root/notebook/local
    deploy:
      resources:
        limits:
          memory: 96G
  stream:
    image: 'daemontus/software-stream:latest'
    ports:
      - "10001:8000"
    volumes:
      - /nfs/ws-daemontus-hdd/software/stream:/root/notebook/remote
      - /media/local/notebook/stream:/root/notebook/local
    deploy:
      resources:
        limits:
          memory: 96G
  scenic:
    image: 'daemontus/software-scenic:latest'
    ports:
      - "10002:8000"
    volumes:
      - /nfs/ws-daemontus-hdd/software/scenic:/root/notebook/remote
      - /media/local/notebook/scenic:/root/notebook/local
    deploy:
      resources:
        limits:
          memory: 96G
  scboolseq:
    image: 'daemontus/software-scboolseq:latest'
    ports:
      - '10003:8000'
    volumes:
      - /nfs/ws-daemontus-hdd/software/scboolseq:/root/notebook/remote
      - /media/local/notebook/scboolseq:/root/notebook/local
    deploy:
      resources:
        limits:
          memory: 96G
  genie3:
    image: 'daemontus/software-genie3:latest'
    ports:
      - '10004:8000'
    volumes:
      - /nfs/ws-daemontus-hdd/software/genie3:/root/notebook/remote
      - /media/local/notebook/genie3:/root/notebook/local
    deploy:
      resources:
        limits:
          memory: 96G
  aeon:
    image: 'daemontus/software-aeon-py:latest'
    ports:
      - '10005:8000'
    volumes:
      - /nfs/ws-daemontus-hdd/software/aeon:/root/notebook/remote
      - /media/local/notebook/aeon:/root/notebook/local
    deploy:
      resources:
        limits:
          memory: 96G
  hakos:
    image: 'daemontus/workspace-base-conda'
    environment:
      WORKSPACE_USER: hakos
      VSCODE_DATA: /home/hakos/data/.vscode_server      
    ports:
      - '10006:8000'
      - '10007:8001'
    volumes:
      - /media/local/hakos:/home/hakos/data
    deploy:
      resources:
        limits:
          memory: 96G